### ISSUE TITLE
Persist current code in localStorage

### ISSUE THREAD

**Issue by R-V-S** [R-V-S/inlineCodeSuite#7]
1. Save the user's code in localStorage on change
2. Provide a "reset" button to return the code to its original state

**Comment by Only1MrAnderson** [comment]
Are you looking to save every keystroke or when a user selects save? I might have some time to take a stab at this

**Comment by R-V-S** [comment]
@Only1MrAnderson Thanks! I actually have this written and ready to deploy, though, so no need! Will have it out the door today.

**Comment by R-V-S** [comment]
Added in 0.7.0
